# ============
# Settings
# ============

SRC_DIR = src
TARGET = latin-c

# Generated by flex/bison
LEX_C   = $(SRC_DIR)/lex.yy.c
PARSER_C = $(SRC_DIR)/parser.tab.c
PARSER_H = $(SRC_DIR)/parser.tab.h

# Source files
SRCS = $(SRC_DIR)/main.c \
       $(SRC_DIR)/ast.c \
       $(SRC_DIR)/interp.c \
       $(PARSER_C) \
       $(LEX_C)

# Object files (same directory as sources)
OBJS = $(SRCS:.c=.o)


# ============
# Build Rules
# ============

all: $(TARGET)

# Bison
$(PARSER_C) $(PARSER_H): $(SRC_DIR)/parser.y
	bison -d -o $(PARSER_C) $(SRC_DIR)/parser.y

# Flex
$(LEX_C): $(SRC_DIR)/lexer.l
	flex -o $(LEX_C) $(SRC_DIR)/lexer.l

# Compile C files to object files
$(SRC_DIR)/%.o: $(SRC_DIR)/%.c
	gcc -Wall -g -c -o $@ $<

# Link
$(TARGET): $(OBJS)
	gcc -Wall -g -o $(TARGET) $(OBJS)


# ============
# Utilities
# ============

clean:
	rm -f $(LEX_C)
	rm -f $(PARSER_C) $(PARSER_H)
	rm -f $(SRC_DIR)/*.o
	rm -f $(TARGET)

.PHONY: all clean
